In [50]:
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.model_selection import train_test_split
from scipy.io import arff
import pandas as pd

df = pd.read_csv("C:/Users/Vineet Kumar/Downloads/kidnapping.csv")
df.head()

STATE/UT  YEAR                  Purpose  Total No. of cases reported  \
0  Andhra Pradesh  2001             For Adoption                            8   
1  Andhra Pradesh  2001              For Begging                            2   
2  Andhra Pradesh  2001         For Camel racing                            0   
3  Andhra Pradesh  2001  For Illicit intercourse                           78   
4  Andhra Pradesh  2001             For marriage                          339   

   Male upto 10 years  Female upto 10 years  Male 10-15 years  \
0                   3                     1                 0   
1                   0                     0                 2   
2                   0                     0                 0   
3                   0                     2                 0   
4                   0                     0                 0   

   Female 10-15 years  Male 15-18 years  Female 15-18 years  ...  \
0                   0                 0                   0  ...   
1                   0                 0                   0  ...   
2                   0                 0                   0  ...   
3                  25                 0                  24  ...   
4                  73                 1                 164  ...   

   Female 30-50 years  Male above 50 years  Female above 50 years  Total Male  \
0                   0                    0                      0           3   
1                   0                    0                      0           2   
2                   0                    0                      0           0   
3                   2                    0                      0           0   
4                   4                    0                      0           7   

   Total Female  Grand Total  Male below 18  Female below 18  \
0             5            8              3                1   
1             0            2              2                0   
2             0            0              0                0   
3            78           78              0               51   
4           332          339              1              237   

   Number of children  Label  
0                   4      F  
1                   2      M  
2                   0      F  
3                  51      F  
4                 238      F  

[5 rows x 23 columns]

In [51]:
df = df.drop(['Total No. of cases reported'], axis=1)
df = df.drop(['Male upto 10 years'], axis=1)
df = df.drop(['Female upto 10 years'], axis=1)
df = df.drop(['Male 10-15 years'], axis=1)
df = df.drop(['Female 10-15 years'], axis=1)
df = df.drop(['Male 15-18 years'], axis=1)
df = df.drop(['Female 15-18 years'], axis=1)
df = df.drop(['Total Male'], axis=1)
df = df.drop(['Female below 18'], axis=1)
df = df.drop(['Total Female'], axis=1)
df = df.drop(['Number of children'], axis=1)
df = df.drop(['Label'], axis=1)

df.head()

STATE/UT  YEAR                  Purpose  Male 18-30 years  \
0  Andhra Pradesh  2001             For Adoption                 0   
1  Andhra Pradesh  2001              For Begging                 0   
2  Andhra Pradesh  2001         For Camel racing                 0   
3  Andhra Pradesh  2001  For Illicit intercourse                 0   
4  Andhra Pradesh  2001             For marriage                 6   

   Female 18-30 years  Male 30-50 years  Female 30-50 years  \
0                   4                 0                   0   
1                   0                 0                   0   
2                   0                 0                   0   
3                  25                 0                   2   
4                  91                 0                   4   

   Male above 50 years  Female above 50 years  Grand Total  Male below 18  
0                    0                      0            8              3  
1                    0                      0            2              2  
2                    0                      0            0              0  
3                    0                      0           78              0  
4                    0                      0          339              1

In [52]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

def encode_df(dataframe):
    le = LabelEncoder()
    for column in dataframe.columns:
        dataframe[column] = le.fit_transform(dataframe[column])
    return dataframe

#encode the dataframe
data=encode_df(df)

print(data)

      STATE/UT  YEAR  Purpose  Male 18-30 years  Female 18-30 years  \
0            1     0        0                 0                   4   
1            1     0        1                 0                   0   
2            1     0        2                 0                   0   
3            1     0        3                 0                  25   
4            1     0       10                 6                  91   
5            1     0        4                 0                  16   
6            1     0        5                 2                   0   
7            1     0        6                11                   4   
8            1     0        7                 0                   0   
9            1     0        8                 0                   0   
10           1     0        9                 0                   0   
11           1     0       11                54                  52   
12           1     0       13               140                 146   
13    

In [53]:
X = df.iloc[:, df.columns != '2']
#X = df.iloc[:, 0:4].values 
y = df.iloc[:, 2].values 

In [54]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)

In [55]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()  
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test)

C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  """


In [56]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
classifier = RandomForestClassifier(n_estimators=100, random_state=0) 

#Train the model using the training sets y_pred=clf.predict(X_test)
classifier.fit(X_train, y_train)  
y_pred = classifier.predict(X_test)  

In [57]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

#Import scikit-learn metrics module for accuracy calculation

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 

# Model Accuracy, how often is the classifier correct?
print(accuracy_score(y_test, y_pred))

[[214   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 201   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0 207   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0 201   1   1   0   0   0   0   0   0   0   0]
 [  0   0   0   1 208   6   0   0   0   0   0   0   0   0]
 [  0   0   0   1   3 201   0   0   0   0   0   0   1   0]
 [  0   0   0   0   0   0 195   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   7 218   0   1   1   0   0   0]
 [  0   0   0   0   0   0   0   3 213   0   0   0   0   0]
 [  0   0   0   0   0   0   1   2   0 206   1   2   0   0]
 [  0   0   0   0   0   0   0   0   0   1 214   0   0   0]
 [  0   0   0   0   0   0   0   0   0   2   2 191   2   1]
 [  0   0   0   0   0   0   0   0   0   0   2  10 202   4]
 [  0   0   0   0   0   0   0   0   0   0   1   2   1 202]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       214
           1       1.00      1.00      1.00       201
          

In [58]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.6, random_state=0)

In [59]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()  
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test)

C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  """


In [60]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
classifier = RandomForestClassifier(n_estimators=100, random_state=0) 

#Train the model using the training sets y_pred=clf.predict(X_test)
classifier.fit(X_train, y_train)  
y_pred = classifier.predict(X_test) 

In [61]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

#Import scikit-learn metrics module for accuracy calculation

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 

# Model Accuracy, how often is the classifier correct?
print(accuracy_score(y_test, y_pred))

[[247   0   0   1   0   0   0   0   0   0   0   0   0   0]
 [  0 243   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0 259   1   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0 249   1   1   0   0   0   0   0   0   0   0]
 [  0   0   0   2 248   7   0   0   0   0   0   0   0   0]
 [  0   0   0   0   2 238  10   0   0   0   1   0   1   0]
 [  0   0   0   0   1   3 218   2   0   0   0   0   0   0]
 [  0   0   0   0   2   0   9 257   1   1   2   0   0   0]
 [  0   0   0   0   0   0   1   3 260   0   0   0   0   0]
 [  0   0   0   0   0   0   1   3   1 237   2   6   0   0]
 [  0   0   0   0   0   0   0   0   0   1 252   0   0   0]
 [  0   0   0   0   0   0   0   0   0   2   1 230   4   1]
 [  0   0   0   0   0   0   0   0   0   0   3  12 241   2]
 [  0   0   0   0   0   0   0   0   0   0   0   7   3 240]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       248
           1       1.00      1.00      1.00       243
          

In [62]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.7, random_state=0)

In [63]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()  
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test)

C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  """


In [64]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
classifier = RandomForestClassifier(n_estimators=100, random_state=0) 

#Train the model using the training sets y_pred=clf.predict(X_test)
classifier.fit(X_train, y_train)  
y_pred = classifier.predict(X_test)  

In [65]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

#Import scikit-learn metrics module for accuracy calculation

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 

# Model Accuracy, how often is the classifier correct?
print(accuracy_score(y_test, y_pred))

[[296   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  1 274   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0 304   2   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0 298   1   2   0   0   0   0   1   0   0   0]
 [  0   0   0   2 277  11   0   0   0   0   0   0   0   0]
 [  0   0   0   1   5 279   3   0   0   0   1   0   1   0]
 [  0   0   0   1   3   2 264   7   0   0   0   1   0   0]
 [  0   0   0   0   1   0  13 290   0   0   1   0   1   0]
 [  0   0   0   0   0   0   2   2 305   0   0   0   0   0]
 [  0   0   0   0   0   0   2   1   1 281   0   6   0   0]
 [  0   0   0   0   0   0   0   0   0   3 286   0   0   0]
 [  0   0   0   0   0   0   0   0   0   1   3 272   5   1]
 [  0   0   0   0   0   0   0   0   0   0   2  14 276   5]
 [  0   0   0   0   0   0   0   0   0   0   1  11   8 276]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       296
           1       1.00      1.00      1.00       275
          

In [66]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.8, random_state=0)

In [67]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()  
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test)

C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  """


In [68]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
classifier = RandomForestClassifier(n_estimators=100, random_state=0) 

#Train the model using the training sets y_pred=clf.predict(X_test)
classifier.fit(X_train, y_train)  
y_pred = classifier.predict(X_test)  

In [69]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

#Import scikit-learn metrics module for accuracy calculation

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 

# Model Accuracy, how often is the classifier correct?
print(accuracy_score(y_test, y_pred))

[[332   0   0   0   0   1   0   0   0   0   0   0   0   0]
 [  0 330   0   1   0   0   0   0   0   0   0   0   0   0]
 [  0   0 349   3   0   0   0   0   0   0   0   0   0   0]
 [  0   0   2 332   2   2   0   0   0   0   1   0   0   0]
 [  0   0   0   8 317   9   0   0   0   0   0   0   0   0]
 [  0   0   0   5  21 292   6   1   0   0   1   0   1   0]
 [  0   0   0   1   4   4 309  10   0   0   0   1   0   0]
 [  0   0   0   0   2   0  23 319   1   1   2   0   1   0]
 [  0   0   0   0   0   0   2   0 335   0   2   0   0   0]
 [  0   0   0   0   0   1  17   3   1 304   3   7   0   0]
 [  0   0   0   0   0   0   0   1   0   2 329   0   0   0]
 [  0   0   0   0   0   0   0   1   0   1   7 304   8   1]
 [  0   0   0   0   0   0   0   1   0   0   5  20 306   6]
 [  0   0   0   0   0   0   0   0   0   0   0  10   7 315]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       333
           1       1.00      1.00      1.00       331
          

In [70]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.9, random_state=0)

In [71]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()  
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test)

C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  """


In [72]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
classifier = RandomForestClassifier(n_estimators=100, random_state=0) 

#Train the model using the training sets y_pred=clf.predict(X_test)
classifier.fit(X_train, y_train)  
y_pred = classifier.predict(X_test)

In [73]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

#Import scikit-learn metrics module for accuracy calculation

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 

# Model Accuracy, how often is the classifier correct?
print(accuracy_score(y_test, y_pred))

[[374   0   0   4   0   5   0   0   0   0   0   0   0   0]
 [  9 363   0   2   0   0   0   0   0   0   0   0   0   0]
 [  0   0 382   4   0   0   0   0   0   0   0   0   0   0]
 [  0   0  16 340  14   2   0   0   0   0   4   0   0   0]
 [  0   0   0  39 329  10   0   0   0   0   0   0   0   0]
 [  0   0   0  12   8 321  23   5   0   0   0   1   3   0]
 [  0   0   0   0   4  14 338   8   0   0   0   0   3   0]
 [  0   0   0   2   8   5  25 335   2   3   8   0   1   0]
 [  0   0   0   0   0   1   1   0 378   0   1   0   0   0]
 [  0   0   0   0   0   1  15   1   1 347   5   9   0   0]
 [  0   0   0   1   0   0   0   0   0   0 354  16   2   0]
 [  0   0   0   0   0   0   0   1   0   1  15 339  15   0]
 [  0   0   0   0   0   0   0   0   0   0  16  37 326   3]
 [  0   0   0   0   0   0   0   0   0   0   5   8   0 355]]
              precision    recall  f1-score   support

           0       0.98      0.98      0.98       383
           1       1.00      0.97      0.99       374
          