In [33]:
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.model_selection import train_test_split
from scipy.io import arff
import pandas as pd

In [34]:
df = pd.read_csv("C:/Users/Vineet Kumar/Downloads/kidnapping.csv")
df.head()

STATE/UT  YEAR                  Purpose  Total No. of cases reported  \
0  Andhra Pradesh  2001             For Adoption                            8   
1  Andhra Pradesh  2001              For Begging                            2   
2  Andhra Pradesh  2001         For Camel racing                            0   
3  Andhra Pradesh  2001  For Illicit intercourse                           78   
4  Andhra Pradesh  2001             For marriage                          339   

   Male upto 10 years  Female upto 10 years  Male 10-15 years  \
0                   3                     1                 0   
1                   0                     0                 2   
2                   0                     0                 0   
3                   0                     2                 0   
4                   0                     0                 0   

   Female 10-15 years  Male 15-18 years  Female 15-18 years  ...  \
0                   0                 0                   0  ...   
1                   0                 0                   0  ...   
2                   0                 0                   0  ...   
3                  25                 0                  24  ...   
4                  73                 1                 164  ...   

   Female 30-50 years  Male above 50 years  Female above 50 years  Total Male  \
0                   0                    0                      0           3   
1                   0                    0                      0           2   
2                   0                    0                      0           0   
3                   2                    0                      0           0   
4                   4                    0                      0           7   

   Total Female  Grand Total  Male below 18  Female below 18  \
0             5            8              3                1   
1             0            2              2                0   
2             0            0              0                0   
3            78           78              0               51   
4           332          339              1              237   

   Number of children  Label  
0                   4      F  
1                   2      M  
2                   0      F  
3                  51      F  
4                 238      F  

[5 rows x 23 columns]

In [35]:
df = df.drop(['Total No. of cases reported'], axis=1)
df = df.drop(['Male upto 10 years'], axis=1)
df = df.drop(['Female upto 10 years'], axis=1)
df = df.drop(['Male 10-15 years'], axis=1)
df = df.drop(['Female 10-15 years'], axis=1)
df = df.drop(['Male 15-18 years'], axis=1)
df = df.drop(['Female 15-18 years'], axis=1)
df = df.drop(['Male 18-30 years'], axis=1)
df = df.drop(['Female 18-30 years'], axis=1)
df = df.drop(['Male 30-50 years'], axis=1)
df = df.drop(['Female 30-50 years'], axis=1)
df = df.drop(['Male above 50 years'], axis=1)
df = df.drop(['Female above 50 years'], axis=1)
df = df.drop(['Total Male'], axis=1)
df = df.drop(['Total Female'], axis=1)
df = df.drop(['Male below 18'], axis=1)
df = df.drop(['Female below 18'],axis=1)
df = df.drop(['Number of children'], axis=1)
df = df.drop(['Purpose'], axis=1)
df = df.drop(['Grand Total'], axis=1)

df.head()

STATE/UT  YEAR Label
0  Andhra Pradesh  2001     F
1  Andhra Pradesh  2001     M
2  Andhra Pradesh  2001     F
3  Andhra Pradesh  2001     F
4  Andhra Pradesh  2001     F

In [40]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

def encode_df(dataframe):
    le = LabelEncoder()
    for column in dataframe.columns:
        dataframe[column] = le.fit_transform(dataframe[column])
    return dataframe

#encode the dataframe
data=encode_df(df)

print(data)

      STATE/UT  YEAR  Label
0            1     0      0
1            1     0      1
2            1     0      0
3            1     0      0
4            1     0      0
5            1     0      0
6            1     0      1
7            1     0      1
8            1     0      0
9            1     0      0
10           1     0      0
11           1     0      1
12           1     0      1
13           1     0      0
14           1     1      0
15           1     1      1
16           1     1      0
17           1     1      0
18           1     1      0
19           1     1      0
20           1     1      1
21           1     1      0
22           1     1      0
23           1     1      0
24           1     1      0
25           1     1      1
26           1     1      1
27           1     1      0
28           1     2      0
29           1     2      0
...        ...   ...    ...
5836        26     9      0
5837        26     9      0
5838        26    10      0
5839        26    10

In [44]:
X = df.iloc[:, 0:2].values 
y = df.iloc[:,-1].values 

In [45]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)

In [46]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()  
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test)

C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [47]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
classifier = RandomForestClassifier(n_estimators=100, random_state=0) 

#Train the model using the training sets y_pred=clf.predict(X_test)
classifier.fit(X_train, y_train)  
y_pred = classifier.predict(X_test)

In [48]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

#Import scikit-learn metrics module for accuracy calculation

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 

# Model Accuracy, how often is the classifier correct?
print(accuracy_score(y_test, y_pred))

[[2255  129]
 [ 493   56]]
              precision    recall  f1-score   support

           0       0.82      0.95      0.88      2384
           1       0.30      0.10      0.15       549

   micro avg       0.79      0.79      0.79      2933
   macro avg       0.56      0.52      0.52      2933
weighted avg       0.72      0.79      0.74      2933

0.7879304466416638


In [49]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.6, random_state=0)

In [50]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()  
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test)

C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [51]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
classifier = RandomForestClassifier(n_estimators=100, random_state=0) 

#Train the model using the training sets y_pred=clf.predict(X_test)
classifier.fit(X_train, y_train)  
y_pred = classifier.predict(X_test)

In [52]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

#Import scikit-learn metrics module for accuracy calculation

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 

# Model Accuracy, how often is the classifier correct?
print(accuracy_score(y_test, y_pred))

[[2661  211]
 [ 582   66]]
              precision    recall  f1-score   support

           0       0.82      0.93      0.87      2872
           1       0.24      0.10      0.14       648

   micro avg       0.77      0.77      0.77      3520
   macro avg       0.53      0.51      0.51      3520
weighted avg       0.71      0.77      0.74      3520

0.774715909090909


In [53]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.7, random_state=0)

In [54]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()  
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test)

C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [55]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
classifier = RandomForestClassifier(n_estimators=100, random_state=0) 

#Train the model using the training sets y_pred=clf.predict(X_test)
classifier.fit(X_train, y_train)  
y_pred = classifier.predict(X_test)

In [56]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

#Import scikit-learn metrics module for accuracy calculation

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 

# Model Accuracy, how often is the classifier correct?
print(accuracy_score(y_test, y_pred))

[[3027  321]
 [ 665   94]]
              precision    recall  f1-score   support

           0       0.82      0.90      0.86      3348
           1       0.23      0.12      0.16       759

   micro avg       0.76      0.76      0.76      4107
   macro avg       0.52      0.51      0.51      4107
weighted avg       0.71      0.76      0.73      4107

0.7599220842464086


In [57]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.8, random_state=0)

In [58]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()  
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test)

C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [59]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
classifier = RandomForestClassifier(n_estimators=100, random_state=0) 

#Train the model using the training sets y_pred=clf.predict(X_test)
classifier.fit(X_train, y_train)  
y_pred = classifier.predict(X_test) 

In [60]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

#Import scikit-learn metrics module for accuracy calculation

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 

# Model Accuracy, how often is the classifier correct?
print(accuracy_score(y_test, y_pred))

[[3319  507]
 [ 710  157]]
              precision    recall  f1-score   support

           0       0.82      0.87      0.85      3826
           1       0.24      0.18      0.21       867

   micro avg       0.74      0.74      0.74      4693
   macro avg       0.53      0.52      0.53      4693
weighted avg       0.72      0.74      0.73      4693

0.740677604943533


In [61]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.9, random_state=0)

In [62]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()  
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test)

C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [63]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
classifier = RandomForestClassifier(n_estimators=100, random_state=0) 

#Train the model using the training sets y_pred=clf.predict(X_test)
classifier.fit(X_train, y_train)  
y_pred = classifier.predict(X_test)

In [64]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

#Import scikit-learn metrics module for accuracy calculation

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 

# Model Accuracy, how often is the classifier correct?
print(accuracy_score(y_test, y_pred))

[[3588  704]
 [ 774  214]]
              precision    recall  f1-score   support

           0       0.82      0.84      0.83      4292
           1       0.23      0.22      0.22       988

   micro avg       0.72      0.72      0.72      5280
   macro avg       0.53      0.53      0.53      5280
weighted avg       0.71      0.72      0.72      5280

0.7200757575757576
